plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'application'
    id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.Instagram'
version = '0.0.1-SNAPSHOT'

application {
    mainClass = 'com.Instagram.Dummy.DummyApplication'  // Replace with actual main class if different
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

spotless {
    java {
        googleJavaFormat() // Use google-java-format for consistent formatting
        target 'src/**/*.java'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.session:spring-session-jdbc'
    implementation 'com.mysql:mysql-connector-j:9.1.0'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

    // Redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis:3.4.0'

    // Validation & Security
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation("org.flywaydb:flyway-core:11.10.5")
    implementation("org.keycloak:keycloak-spring-boot-starter:25.0.3")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server:4.0.0-M1")
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    // Reactive Web
    implementation 'org.springframework:spring-webflux:6.1.14'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
